#ifndef FVIZ_CORE_RESULT_H
#define FVIZ_CORE_RESULT_H

#include <FViz/Core/FVizApi.h>

FVIZ_EXTERN_C_BEGIN

typedef enum FVizResult
{
    FVIZ_OK = 0,
    FVIZ_ERROR_INVALID_ARGUMENT = 1,
    FVIZ_ERROR_OUT_OF_MEMORY = 2,
    FVIZ_ERROR_NOT_SUPPORTED = 3,
    FVIZ_ERROR_IO = 4,
    FVIZ_ERROR_INTERNAL = 5,
    FVIZ_ERROR_OVERFLOW = 6,
    FVIZ_ERROR_INVALID_STATE = 7,
    FVIZ_ERROR_NOT_FOUND = 8,
    FVIZ_ERROR_BUSY = 9,
    FVIZ_ERROR_PARSE = 10,
    FVIZ_ERROR_GRAPHICS = 11
} FVizResult;

FVIZ_EXTERN_C_END

#endif /* FVIZ_CORE_RESULT_H */
