#ifndef FVIZ_INTERNAL_RENDERING_ACTOR_PRIVATE_H
#define FVIZ_INTERNAL_RENDERING_ACTOR_PRIVATE_H

#include <FViz/Core/FVizObjectPrivate.h>
#include <FViz/Math/FVizQuat.h>
#include <FViz/Math/FVizVec3.h>
#include <FViz/Rendering/FVizActor.h>

struct FVizActor
{
    FVizObject base;
    FVizMapper* mapper;
    FVizGlyphMapper* glyph_mapper;
    FVizVolumeMapper* volume_mapper;
    FVizObserverTag mapper_modified_tag;
    FVizObserverTag glyph_mapper_modified_tag;
    FVizObserverTag volume_mapper_modified_tag;
    FVizObserverTag user_transform_modified_tag;
    float color[3];
    FVizBool visible;
    FVizBool pickable;
    FVizBool wireframe;
    FVizBool edge_visible;
    float opacity;
    float edge_color[3];
    float line_width;
    float line_depth_bias;
    FVizLineCap line_cap;
    FVizLineJoin line_join;
    float line_miter_limit;
    float line_dash_length;
    float line_gap_length;
    float line_dash_phase;
    FVizBool line_scalar_coloring;
    FVizBool point_visible;
    float point_size;
    FVizPointShape point_shape;
    float point_color[3];
    FVizBool point_scalar_coloring;
    float ambient;
    float diffuse;
    float specular;
    float specular_power;
    FVizShadingMode shading_mode;
    FVizCullMode cull_mode;
    FVizCoincidentTopologyMode coincident_mode;
    FVizBool offset_faces;
    float polygon_offset_factor;
    float polygon_offset_units;
    float line_offset_factor;
    float line_offset_units;
    float point_offset_units;
    float z_shift;
    FVizBool depth_test;
    FVizBool depth_write;
    FVizDepthFunction depth_function;
    float depth_range_minimum;
    float depth_range_maximum;
    int32_t render_layer;
    int32_t render_priority;
    FVizRenderPassStage pass_order;
    FVizOverlayTopologyMode overlay_mode;
    uint32_t topology_data_flags;
    FVizVec3 position;
    FVizQuat orientation;
    FVizVec3 scale;
    FVizTransform* user_transform;
    FVizBounds world_bounds_cache;
    FVizMTime world_bounds_geometry_mtime;
    FVizMTime world_bounds_user_transform_mtime;
    uint64_t transform_revision;
    uint64_t world_bounds_transform_revision;
    FVizBool world_bounds_cache_initialized;
};

#endif /* FVIZ_INTERNAL_RENDERING_ACTOR_PRIVATE_H */
