function(fviz_add_example target source)
    add_executable(${target} ${source})
    target_link_libraries(${target} PRIVATE FEAViz::FEAViz)
    fviz_apply_compiler_options(${target})
    fviz_set_target_output_directories(${target})
endfunction()

fviz_add_example(FVizExampleVersion 01_Core/version_info.c)
fviz_add_example(FVizExampleCoreRuntime 01_Core/core_runtime.c)
fviz_add_example(FVizExampleContainers 02_Data/containers.c)
fviz_add_example(FVizExamplePolyData 03_Mesh/poly_data.c)
fviz_add_example(FVizExampleLoadMesh 04_IO/load_mesh.c)
fviz_add_example(FVizViewer 05_Rendering/viewer.c)
fviz_add_example(FVizExampleSimpleModel 06_Tutorial/simple_model.c)
fviz_add_example(FVizExampleScalarColoring 07_ScalarColoring/scalar_coloring.c)
fviz_add_example(FVizExampleFEASlice 08_FEASlice/fea_slice.c)
fviz_add_example(FVizExampleFEAViewer 09_FEAViewer/fea_viewer.c)
fviz_add_example(FVizExamplePicking 10_Picking/picking.c)
fviz_add_example(FVizExampleVTUViewer 11_VTUViewer/vtu_viewer.c)
fviz_add_example(FVizExampleContourLines 12_ContourLines/contour_lines.c)
fviz_add_example(FVizExampleBentBeam 13_BentBeam/bent_beam.c)

set_target_properties(FVizViewer PROPERTIES OUTPUT_NAME "FEAVizViewer")
set_target_properties(FVizExampleSimpleModel PROPERTIES OUTPUT_NAME "FEAVizSimpleModel")
set_target_properties(FVizExampleScalarColoring PROPERTIES OUTPUT_NAME "FEAVizScalarColoring")
set_target_properties(FVizExampleFEASlice PROPERTIES OUTPUT_NAME "FEAVizFEASlice")
set_target_properties(FVizExampleFEAViewer PROPERTIES OUTPUT_NAME "FEAVizFEAViewer")
set_target_properties(FVizExamplePicking PROPERTIES OUTPUT_NAME "FEAVizPicking")
set_target_properties(FVizExampleVTUViewer PROPERTIES OUTPUT_NAME "FEAVizVTUViewer")
set_target_properties(FVizExampleContourLines PROPERTIES OUTPUT_NAME "FEAVizContourLines")
set_target_properties(FVizExampleBentBeam PROPERTIES OUTPUT_NAME "FEAVizBentBeam")

if(FVIZ_BUILD_TESTS)
    add_test(NAME FViz.Examples.BentBeam COMMAND FVizExampleBentBeam --validate)
endif()
