#include <stdio.h>

#include <FViz/Core/FVizError.h>
#include <FViz/IO/FVizPLYWriter.h>

#include <FViz/Core/FVizErrorInternal.h>

FVizResult fviz_ply_write(const char* file_path, const FVizPolyData* poly_data, FVizPLYOutputMode output_mode)
{
    FILE* file;
    const FVizVec3* points;
    const uint32_t* triangles;
    FVizSize point_count;
    FVizSize triangle_count;
    FVizSize i;
    FVizBool ok = FVIZ_TRUE;
    if (file_path == NULL || poly_data == NULL ||
        (output_mode != FVIZ_PLY_OUTPUT_ASCII && output_mode != FVIZ_PLY_OUTPUT_BINARY_LITTLE_ENDIAN))
        return FVIZ_ERROR_INVALID_ARGUMENT;
    if (fviz_poly_data_validate(poly_data) != FVIZ_OK) return fviz_last_error_code();
    file = fopen(file_path, "wb");
    if (file == NULL) return FVIZ_ERROR_IO;
    point_count = fviz_poly_data_point_count(poly_data);
    triangle_count = fviz_poly_data_triangle_count(poly_data);
    points = fviz_poly_data_points(poly_data);
    triangles = fviz_poly_data_triangle_indices(poly_data);
    if (fprintf(file,
                "ply\nformat %s 1.0\ncomment generated by FEAViz\n"
                "element vertex %zu\nproperty float x\nproperty float y\nproperty float z\n"
                "element face %zu\nproperty list uchar uint vertex_indices\nend_header\n",
                output_mode == FVIZ_PLY_OUTPUT_ASCII ? "ascii" : "binary_little_endian", point_count,
                triangle_count) < 0)
        ok = FVIZ_FALSE;
    if (output_mode == FVIZ_PLY_OUTPUT_ASCII)
    {
        for (i = 0u; ok != FVIZ_FALSE && i < point_count; ++i)
            if (fprintf(file, "%.9g %.9g %.9g\n", (double)points[i].x, (double)points[i].y, (double)points[i].z) < 0)
                ok = FVIZ_FALSE;
        for (i = 0u; ok != FVIZ_FALSE && i < triangle_count; ++i)
            if (fprintf(file, "3 %u %u %u\n", triangles[i * 3u], triangles[i * 3u + 1u], triangles[i * 3u + 2u]) < 0)
                ok = FVIZ_FALSE;
    }
    else
    {
        for (i = 0u; ok != FVIZ_FALSE && i < point_count; ++i)
            if (fwrite(&points[i], sizeof(float), 3u, file) != 3u) ok = FVIZ_FALSE;
        for (i = 0u; ok != FVIZ_FALSE && i < triangle_count; ++i)
        {
            const uint8_t count = 3u;
            if (fwrite(&count, sizeof(count), 1u, file) != 1u ||
                fwrite(&triangles[i * 3u], sizeof(uint32_t), 3u, file) != 3u)
                ok = FVIZ_FALSE;
        }
    }
    if (fclose(file) != 0) ok = FVIZ_FALSE;
    if (ok == FVIZ_FALSE)
    {
        fviz_internal_set_error(FVIZ_ERROR_IO, "failed while writing PLY file");
        return FVIZ_ERROR_IO;
    }
    return FVIZ_OK;
}
