include_guard(GLOBAL)

function(fviz_apply_sanitizers target)
    if(MSVC)
        if(FVIZ_ENABLE_ASAN)
            target_compile_options(${target} PRIVATE /fsanitize=address)
            target_link_options(${target} PRIVATE /fsanitize=address)
        endif()
        if(FVIZ_ENABLE_UBSAN)
            message(WARNING "FEAViz: UBSan is not configured for MSVC in Phase 0")
        endif()
        return()
    endif()

    set(_fviz_sanitizers "")
    if(FVIZ_ENABLE_ASAN)
        list(APPEND _fviz_sanitizers "address")
    endif()
    if(FVIZ_ENABLE_UBSAN)
        list(APPEND _fviz_sanitizers "undefined")
    endif()

    if(_fviz_sanitizers)
        list(JOIN _fviz_sanitizers "," _fviz_sanitizer_list)
        target_compile_options(${target} PRIVATE -fno-omit-frame-pointer "-fsanitize=${_fviz_sanitizer_list}")
        target_link_options(${target} PRIVATE "-fsanitize=${_fviz_sanitizer_list}")
    endif()
endfunction()
